x-service: &service
  image: pnpm
  build:
    context: .
    dockerfile: docker/pnpm.dockerfile
  working_dir: /app
  user: 1000:1000
  restart: on-failure
  volumes:
    - ./:/app

version: '3'

services:
  booking-api:
    <<: *service
    command: pnpm serve booking-api
    environment:
      PORT: 8080
    ports:
      - 8080:8080

  kombinator-api:
    <<: *service
    command: pnpm serve kombinator-api
    environment:
      PORT: 8080
    ports:
      - 8081:8080

  webapp:
    <<: *service
    command: pnpm serve webapp -- --port $$PORT
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - booking-api
      - kombinator-api
